import type { Drug, IVCompatibility } from '@/types';

export const mockDrugs: Drug[] = [
  {
    id: 'drug-1',
    genericName: 'Paracetamol',
    tradeName: 'Tylenol',
    dosageForm: 'tablet',
    strength: '500 mg',
    route: ['oral'],
    therapeuticClass: 'Analgesic',
    indication: 'ลดไข้ บรรเทาปวด',
    contraindication: 'ระวังในตับทำงานบกพร่อง',
    sideEffects: 'คลื่นไส้ ผื่นแพ้',
    interactions: 'แอลกอฮอล์ ยากลุ่ม warfarin',
    pregnancyCategory: 'B',
    g6pdSafe: true,
    storage: 'เก็บที่อุณหภูมิห้อง',
    pricePerUnit: 1.5,
    status: 'all_rights',
    notes: 'ขนาดสูงสุดผู้ใหญ่ 4 กรัม/วัน',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'drug-2',
    genericName: 'Ceftriaxone',
    tradeName: 'Rocephin',
    dosageForm: 'injection',
    strength: '1 g/vial',
    route: ['IV', 'IM'],
    therapeuticClass: 'Antibiotic',
    indication: 'ติดเชื้อแบคทีเรียหลายระบบ',
    contraindication: 'ห้ามผสมกับ calcium-containing solutions ใน neonate',
    sideEffects: 'ท้องเสีย ผื่นแพ้',
    interactions: 'Calcium solutions',
    pregnancyCategory: 'B',
    g6pdSafe: true,
    storage: 'ป้องกันแสง',
    pricePerUnit: 68,
    status: 'all_rights',
    notes: 'ระวัง biliary sludge',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    updatedBy: 'system',
  },
  {
    id: 'drug-3',
    genericName: 'Primaquine',
    tradeName: 'Primaquine',
    dosageForm: 'tablet',
    strength: '15 mg',
    route: ['oral'],
    therapeuticClass: 'Antimalarial',
    indication: 'รักษาและกำจัด hypnozoite ของ malaria',
    contraindication: 'G6PD deficiency',
    sideEffects: 'hemolysis, คลื่นไส้',
    interactions: 'ยาที่ทำให้เม็ดเลือดแดงแตก',
    pregnancyCategory: 'D',
    g6pdSafe: false,
    storage: 'เก็บที่แห้ง',
    pricePerUnit: 11,
    status: 'ned_only',
    notes: 'ต้องคัดกรอง G6PD ก่อนใช้',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    updatedBy: 'system',
  },
];

export const mockCompat: IVCompatibility[] = [
  {
    id: 'compat-1',
    drugAId: 'drug-2',
    drugBId: 'drug-1',
    solution: 'NSS',
    compatible: 'Y',
    timeLimitHr: 24,
    temperature: 'room_temp',
    notes: 'ไม่มี precipitate ในช่วงเวลาที่ทดสอบ',
    reference: "Trissel's",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'compat-2',
    drugAId: 'drug-2',
    drugBId: 'drug-3',
    solution: 'D5W',
    compatible: 'Conditional',
    timeLimitHr: 1,
    temperature: 'protected_light',
    notes: 'ให้แยก line ถ้า concentration สูง',
    reference: 'King Guide',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
